name: Update Plant Growth

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allows pushing updates

jobs:
  update-growth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python script/update_plants.py  # Corrected path // was not included before

      - name: Commit and push changes
        env:
          GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
          git add images/
          git commit -m "Automated plant growth update" || echo "No changes to commit"
          echo "${GH_PAT_TOKEN}" | gh auth login --with-token
          git push origin main
